### ISSUE TITLE
Broken as of end of 18th July

### ISSUE THREAD

**Issue by GrahamCampbell** [adilosa/awswhatsnew#11]
There seems to be no new tweets after mid-afternoon on the 18th July.

**Comment by adilosa** [comment]
Hey, sorry I didn't see this before. Will take a look this weekend!

**Comment by adilosa** [comment]
Looks like it's related to this: https://github.com/bear/python-twitter/issues/722

**Comment by adilosa** [comment]
Working on it. In their infinite wisdom, Twitter changed ... something with the api keys so I mainly had to regenerate them all and change some permissions that somehow went missing. I expect it to be largely fixed now, although the new rate limit of 50/day is potentially a bit limiting during re:Invent. Not willing to give twitter $100/mo tho. Currently, it's all timed out as failed requests apparently count against the limits. Will see what happens with it tomorrow when the cap resets

**Comment by adilosa** [comment]
Seems to be working again! At least, a tweet was successfully posted. Will update to better handle whatever the new silent rate limits are. Also, apparently tweets longer than 280 chars are not supported with the new API and it's been an ongoing issue for years: https://twittercommunity.com/t/how-to-post-280-4000-characters-via-api-v2/191156. So I'll just make sure they're short enough

**Comment by adilosa** [comment]
Alright, I think we're back. And just in time for reinvent. Happy thanksgiving 🦃!
