### ISSUE TITLE
Bug: Tweets have extaneous article extract.

### ISSUE THREAD

**Issue by misterjoshua** [adilosa/awswhatsnew#12]
There seems to be a problem with the second line of the posts that went out today. All seem to reference the same, unrelated CodeWhisperer announcement:

![image](https://github.com/adilosa/awswhatsnew/assets/644092/a453dac8-9add-4d8a-85de-1ae19be1c942)

**Comment by adilosa** [comment]
Oh! I must have messed that up, thanks. Will fix shortly. Damn Copilot 😛

**Comment by adilosa** [comment]
I'm not immediately sure why that is happening. Will see if it continues once the rate limits unblock

**Comment by adilosa** [comment]
Found it, fixing now

**Comment by adilosa** [comment]
Ok should be fixed now, thanks!
